// Selected direction: sidebar introduction and a collection of projects.
// The original design variants are preserved on prototype/portfolio-variants.
import './style.css';
import { repositories } from './github-repositories.js';
import { initializeMotion } from './motion.js';

const app = document.querySelector('#app');
const status = '<span class="status"><i></i> Currently learning &amp; building</span>';
const character = () => `<div class="scene portrait"><img src="/images/oakkar-character-v2.png" alt="Full-length stylized character of Oakkar with curly hair, silver glasses, a black hoodie, and black sneakers" width="1122" height="1402" fetchpriority="high" /></div>`;
const projects = [
  { name: 'PlayKit', status: 'Live', description: 'My friends and I had cards, but no chips or cash. That became PlayKit: a toolkit for game nights, with poker chip tracking, a chess clock, scorekeeping, tournaments, Undercover, and Imposter. Play on one shared device, or let friends join supported games on their own phones.', detail: 'Six tools for game nights · Try PlayKit', url: 'https://playkit.oakkarphyo.com', repoUrl: 'https://github.com/okhay-p/playkit', image: 'poker-helper-v1.webp', alt: 'Clay-style poker chips and playing cards on a lilac backdrop', color: 'purple' },
  { name: 'SSH manager', status: 'Private tool', description: 'Remembering server IPs, usernames, and key files got old. This CLI reads a JSON config so I can connect with one command: sshm server_alias.', detail: 'A small tool I actually use', image: 'ssh-manager-v1.webp', alt: 'A terracotta key with a miniature terminal and connected server blocks', color: 'peach' },
  { name: 'Home server', status: 'Personal setup', description: 'An old laptop now runs long agent tasks so my everyday laptop doesn’t have to. T3 helps me manage Codex and OpenCode; Hermes handles research and server setup, with Tailscale for access when I’m out.', detail: 'Hermes / Codex / OpenCode / T3 / Tailscale', image: 'home-server-v1.webp', alt: 'A miniature laptop, server blocks, and router in soft sage and cream', color: 'green' },
  { name: 'AkashaLearn', status: 'Archived', description: 'I built an AI lesson app to learn Go and experiment with LLM integration. It’s no longer maintained and the app is offline, but the code is still around.', detail: 'Go / React / LLM integration · View code', url: 'https://github.com/okhay-p/akasha-client', image: 'akashalearn-v1.webp', alt: 'A stack of pastel books with open pages and a golden AI sparkle', color: 'purple' },
];
function ProjectCard(project) {
  const tag = project.repoUrl ? 'article' : project.url ? 'a' : 'article';
  const attributes = tag === 'a' ? ` href="${project.url}" target="_blank" rel="noopener noreferrer"` : '';
  const visual = `<div class="collection-art ${project.color}"><img class="project-image" src="/images/${project.image}" alt="${project.alt}" width="1200" height="800" loading="lazy" decoding="async" /><span class="project-status">${project.status}</span></div><div class="collection-meta"><div><h2>${project.name}</h2><p>${project.detail}</p></div>${project.url ? '<span aria-hidden="true">↗</span>' : ''}</div>`;
  const primary = project.repoUrl ? `<a class="project-primary" href="${project.url}" target="_blank" rel="noopener noreferrer">${visual}</a>` : visual;
  const source = project.repoUrl ? `<p class="project-links"><a href="${project.repoUrl}" target="_blank" rel="noopener noreferrer">View code on GitHub ↗</a></p>` : '';
  return `<${tag} class="collection-card"${attributes}>${primary}<p class="project-description">${project.description}</p>${source}</${tag}>`;
}
const escape = text => String(text).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const githubLink = '<a class="github-profile" href="https://github.com/okhay-p" target="_blank" rel="noopener noreferrer">More on GitHub ↗</a>';
function Skills() {
  return `<section class="skills-section" id="skills"><div class="eyebrow">HOW I BUILD</div><div class="skills-intro"><h2>A curious mind.<br>A practical toolkit.</h2><p>Code, craft, and AI-assisted development.</p></div><div class="skills-groups"><div><h3>Development</h3><div class="skill-tags">${['TypeScript','React','Astro','Go','Python'].map(name=>`<span>${name}</span>`).join('')}</div></div><div><h3>AI-assisted development</h3><div class="skill-tags agent-tags">${[{name:'Hermes',logo:'hermes.svg'},{name:'OpenCode',logo:'opencode.svg'},{name:'Codex',logo:'codex.png'}].map(({name,logo})=>`<span><img class="agent-logo ${name.toLowerCase()}-logo" src="/images/logos/${logo}" alt="" aria-hidden="true" width="24" height="24" />${name}</span>`).join('')}</div></div></div></section>`;
}
function RepositoryList() {
  return `<section class="repository-section" id="repositories"><div class="section-heading"><h2>Public repositories <span>/ ${repositories.length}</span></h2>${githubLink}</div><div class="repo-list">${repositories.map(repo=>`<a href="${escape(repo.url)}" target="_blank" rel="noopener noreferrer"><span class="repo-name">${escape(repo.name)}${repo.isFork?'<small>FORK</small>':''}</span><span class="repo-language">${escape(repo.primaryLanguage?.name || 'Resources')}</span><span aria-hidden="true">↗</span></a>`).join('')}</div></section>`;
}
function Portfolio() {
  return `<div class="c-layout"><aside class="c-sidebar"><a class="wordmark" href="/">oakkar</a><div><span class="eyebrow">DEVELOPER. BUILDER.<br>OCCASIONAL DAYDREAMER.</span><h1>Learning by<br>building.</h1><p>First-year Computer Science student at Singapore Management University.</p>${status}</div><div class="c-sidebar-bottom"><a href="#about">A bit about me ↗</a><a href="#skills">My toolkit ↗</a><a href="https://www.linkedin.com/in/oakkarphyo/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/okhay-p" target="_blank" rel="noopener noreferrer">GitHub ↗</a><span>LEARNING / BUILDING / EXPLORING</span></div></aside><section class="c-content" id="work"><div class="c-heading"><span>THE COLLECTION</span><span>SMALL TOOLS & SIDE QUESTS</span></div><div class="collection"><div class="collection-card card-large"><div class="collection-art blue">${character()}<span class="collection-sticker">A LITTLE HUMAN TOUCH</span></div><div class="collection-meta"><div><h2>Hello, I’m Oakkar.</h2><p>Learning things. Making things. Mostly because I can.</p></div></div></div>${projects.map(ProjectCard).join('')}</div>${Skills()}${RepositoryList()}<section class="c-about" id="about"><h2>A curious mind.<br>A hands-on approach.</h2><p>I’m Oakkar, a first-year Computer Science student at Singapore Management University. I build small tools, learn things along the way, and occasionally make life a little easier. Mostly because I can.</p><p>Outside of code, I play football. I also used to make 3D models and animations—some of that past life lives on Instagram.</p><a class="instagram-card" href="https://www.instagram.com/noooidea.creative/" target="_blank" rel="noopener noreferrer" aria-label="See my past 3D models and animations on Instagram"><img src="/images/instagram-creative-card-v1.png" alt="A miniature gallery inspired by my 3D renders: a riverside shop, snowman, moon-and-stars switch, and framed abstract print" width="1536" height="1024" loading="lazy" /><div class="instagram-card-caption"><div><h3>A past life in polygons.</h3><span>@noooidea.creative · 3D & animation</span></div><span aria-hidden="true">↗</span></div></a><div class="about-socials"><a class="github-profile" href="https://www.linkedin.com/in/oakkarphyo/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>${githubLink}</div></section><footer><span>© 2026 Oakkar</span><span>STAY CURIOUS.</span></footer></section></div>`;
}
app.innerHTML = Portfolio();
initializeMotion(app);
